# Generated by Django 5.0.6 on 2024-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="collection_name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
