# Generated by Django 5.0.6 on 2024-08-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_collection_name_collection_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="title",
            new_name="collection_name",
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
