# Generated by Django 5.0.6 on 2024-08-12 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_releaselist_delete_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaselist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
