# Generated by Django 5.0.6 on 2024-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_releaselist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="release_data",
            field=models.JSONField(default=dict),
        ),
    ]
